//Idee: FIELD bekommt Attribut: shipIndex
//2 Array: Inventory(Ships) speichert auch x und y werte des schiffes
//Wird ein schiff platziert wird das Field mit dem shipIndex belegt
//Wird ein schiff umplaziert: Schaue auf board welches schiff auf dem Field ist(shipIndex), finde im inventory, ändere ship index auf board.
//Probleme: Wie gehe ich mit dragndrop um, wie gehe ich mit inventar um?

export const FIELD = [
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
];
export const OPPONENT_FIELD = [
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
  [
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
    {
      isShip: false,
      isBombed: false,
      isHit: false,
      shipIndex: undefined,
    },
  ],
];

export const INVENTORY = [
  {
    name: "Schlachter",
    length: 5,
    horizontal: true,
  },
  {
    name: "Kreuzer 1",
    length: 4,
    horizontal: true,
  },
  {
    name: "Kreuzer 2",
    length: 4,
    horizontal: true,
  },
  {
    name: "Zerstörer 1",
    length: 3,
    horizontal: true,
  },
  {
    name: "Zerstörer 2",
    length: 3,
    horizontal: true,
  },
  {
    name: "Zerstörer 3",
    length: 3,
    horizontal: true,
  },
  {
    name: "U-Boot 1",
    length: 2,
    horizontal: true,
  },
  {
    name: "U-Boot 2",
    length: 2,
    horizontal: true,
  },
  {
    name: "U-Boot 3",
    length: 2,
    horizontal: true,
  },
  {
    name: "U-Boot 4",
    length: 2,
    horizontal: true,
  },
];

export const OPPONENT_SHIPS = [
  {
    name: "Schlachter",
    length: 5,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "Kreuzer 1",
    length: 4,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "Kreuzer 2",
    length: 4,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "Zerstörer 1",
    length: 3,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "Zerstörer 2",
    length: 3,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "Zerstörer 3",
    length: 3,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "U-Boot 1",
    length: 2,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "U-Boot 2",
    length: 2,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "U-Boot 3",
    length: 2,
    horizontal: true,
    destroyed: false,
  },
  {
    name: "U-Boot 4",
    length: 2,
    horizontal: true,
    destroyed: false,
  },
];

export const GAME_CONDITIONS = {
  PLAY: {
    desc: "Du bist an der Reihe!",
  },
  WAIT_FOR_BOMB: {
    desc: "Dein Gegner ist an der Reihe!",
  },
  WAIT_FOR_PLAYER: {
    desc: "Warte auf deinen Mitspieler",
  },
  SELECT_FIELD: {
    desc: "Verteile deine Schiffe auf dem Spielfeld!",
  },
};

export const BOARD_WIDTH = 10;
export const BOARD_HEIGHT = 10;
